### ISSUE TITLE
Please add newer Pi 4 board revision 'c03112'

### ISSUE THREAD

**Issue by StefanHamminga** [veyeimaging/raspberrypi#3]
https://github.com/veyeimaging/raspberrypi/blob/2b088f23d69d6ea10799191a9b731f030c680ca6/i2c_cmd/bin/camera_i2c_config#L102

Please add `c03112` to the list of boards here for newer Raspberry Pi 4 4GB revisions.

**Comment by mmxuxp** [comment]
> https://github.com/veyeimaging/raspberrypi/blob/2b088f23d69d6ea10799191a9b731f030c680ca6/i2c_cmd/bin/camera_i2c_config#L102
> 
> Please add `c03112` to the list of boards here for newer Raspberry Pi 4 4GB revisions.

done，thank you!
